---
- name: Install Docker
  hosts: server_belajar
  become: true
  become_method: sudo
  tasks:
    - name: Update repository
      ansible.builtin.apt:
        update_cache: true
    - name: Install Docker.io
      ansible.builtin.apt:
        name: docker.io
        state: present
    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started
    - name: Run hello-world container
      command: docker run hello-world